# NeuraPulse Configuration

# System Monitor Settings
monitoring:
  update_interval: 0.1  # seconds
  max_processes: 1000
  track_io: true
  track_threads: true
  track_priority: true

# Quantum Scheduler Settings
quantum:
  num_qubits: 4
  annealing_rate: 0.95
  min_temperature: 0.01
  optimization_interval: 1.0  # seconds
  quantum_weight: 0.7
  resource_weight: 0.3

# Synergy Core Settings
synergy:
  cpu_threshold: 80.0
  memory_threshold: 85.0
  io_threshold: 1000000
  action_threshold: 0.7
  optimization_interval: 0.5  # seconds
  max_optimized_processes: 5
  critical_processes:
    - "system"
    - "svchost.exe"
    - "explorer.exe"

# Continual Learner Settings
ai:
  learning_rate: 0.001
  batch_size: 32
  sequence_length: 10
  drift_detection_threshold: 0.8
  anomaly_detection_threshold: 0.8
  model_update_interval: 1.0  # seconds
  max_history_size: 1000

# GUI Settings
gui:
  window_width: 1200
  window_height: 800
  sphere_size: 400
  update_interval: 16  # milliseconds (~60 FPS)
  rotation_speed: 0.01
  view_modes:
    - "Resource Usage"
    - "Process Dependencies"
    - "Quantum States"
  gesture_recognition:
    confidence_threshold: 0.7
    update_interval: 100  # milliseconds

# Logging Settings
logging:
  level: INFO
  file: "neurapulse.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance Settings
performance:
  max_memory_usage: 1024  # MB
  max_cpu_usage: 80  # percent
  enable_gpu: true
  num_worker_threads: 4
  cache_size: 1000  # items

# Security Settings
security:
  require_admin: true
  allowed_processes: []  # empty list means all processes
  blocked_processes: []
  max_api_calls: 1000  # per second
  enable_encryption: true
  encryption_key: ""  # should be set in production

# Network Settings
network:
  enable_remote_monitoring: false
  port: 8080
  max_connections: 10
  timeout: 30  # seconds
  ssl_enabled: false
  allowed_ips: []

# Storage Settings
storage:
  data_directory: "data"
  max_history_days: 30
  compression_enabled: true
  backup_interval: 86400  # seconds (24 hours)
  max_backup_size: 1073741824  # 1GB 